globalThis.TrainingRecorderMSG = {
  CONTENT_START: "CONTENT_START",
  CONTENT_STOP: "CONTENT_STOP",
  CONTENT_GET_EVENTS: "CONTENT_GET_EVENTS",
  CONTENT_OVERLAY_START: "CONTENT_OVERLAY_START",
  CONTENT_OVERLAY_STOP: "CONTENT_OVERLAY_STOP",
  CAPTURE_FRAMES: "CAPTURE_FRAMES",
  STOP_AND_PROCESS: "STOP_AND_PROCESS",
};

if (typeof window !== "undefined") {
  window.TrainingRecorderMSG = globalThis.TrainingRecorderMSG;
}
